const challenges = [
  ["Funciones", "¿Qué es una función?", "choice", "Selecciona la definición que corresponde a la Lección 2.", ["Un bloque de instrucciones diseñado para realizar una tarea específica.", "Una hoja de cálculo con varias filas.", "Un objeto creado a partir de una clase."], 0, "Una función se crea para realizar una tarea específica y puede reutilizarse."],
  ["Funciones", "La ventaja de reutilizar", "choice", "¿Por qué resulta útil crear una función para una tarea que se repite?", ["Porque se crea una vez y puede utilizarse todas las veces que sea necesario.", "Porque elimina la necesidad de usar datos.", "Porque convierte automáticamente una lista en diccionario."], 0, "La idea central es evitar repetir las mismas instrucciones cada vez."],
  ["Funciones", "Completa la función de avance", "fill", "Completa únicamente la palabra reservada que falta para definir la función.", "___ calcular_avance(meta, realizado):\n    porcentaje = (realizado / meta) * 100\n    return porcentaje", "def", "En Python, una función se define con la palabra def."],
  ["Funciones", "Identifica el nombre", "choice", "En `calcular_avance(meta, realizado)`, ¿cuál es el nombre de la función?", ["meta", "calcular_avance", "realizado"], 1, "El nombre de la función es calcular_avance."],
  ["Funciones", "Reconoce los parámetros", "multi", "Escribe los dos parámetros de `calcular_avance(meta, realizado)` separados por una coma.", "def calcular_avance(___, ___):\n    porcentaje = (realizado / meta) * 100\n    return porcentaje", ["meta", "realizado"], "meta y realizado son los parámetros indicados en el ejemplo."],
  ["Funciones", "¿Qué hace return?", "choice", "Según el ejemplo de la Lección 2, ¿qué hace `return`?", ["Devuelve el resultado procesado por la función.", "Crea una lista vacía.", "Define el nombre de una clase."], 0, "return devuelve el resultado de la función."],
  ["Funciones", "Completa el resultado", "fill", "Completa únicamente el dato que la función debe devolver.", "def calcular_avance(meta, realizado):\n    porcentaje = (realizado / meta) * 100\n    return ___", "porcentaje", "La función devuelve el valor almacenado en porcentaje."],
  ["Funciones", "¿Qué significa modularidad?", "choice", "Selecciona la explicación dada en el material.", ["Dividir un problema grande en tareas pequeñas y claras.", "Guardar todos los datos en una sola variable.", "Usar exclusivamente clases en todo programa."], 0, "Modularidad significa dividir un problema grande en tareas pequeñas y claras."],
  ["Funciones", "Funciones de un sistema", "choice", "¿Cuál conjunto aparece como ejemplo de tareas separadas dentro de un sistema de seguimiento?", ["registrar_actividad, calcular_avance y generar_resumen", "marca, modelo y color", "GREAT, MPAS y DARE"], 0, "El ejemplo divide el sistema en registrar actividades, calcular avances y generar un resumen."],
  ["Funciones", "Idea clave de modularidad", "choice", "¿Cuál secuencia coincide con la IDEA CLAVE de la Lección 2?", ["Problema grande → dividir en tareas → crear funciones → reutilizar las funciones", "Crear objeto → borrar datos → repetir código", "Lista → HTML → color → método"], 0, "La idea clave conecta problema, división de tareas, funciones y reutilización."],

  ["Datos", "¿Qué permite una lista?", "choice", "Selecciona la definición estudiada.", ["Guardar varios elementos dentro de una misma variable.", "Guardar únicamente un número.", "Definir acciones de un objeto."], 0, "Una lista agrupa varios elementos en una misma variable."],
  ["Datos", "Completa la lista de programas", "fill", "Completa únicamente el primer elemento de la lista tal como aparece en el material.", "programas = [\"___\", \"MPAS\", \"DARE\", \"PSCC\", \"VIF\"]", "GREAT", "La lista del ejemplo inicia con GREAT."],
  ["Datos", "Python cuenta desde cero", "choice", "En la lista `programas`, ¿qué elemento corresponde a `programas[0]`?", ["MPAS", "GREAT", "VIF"], 1, "Python comienza a contar las posiciones desde 0; por eso programas[0] es GREAT."],
  ["Datos", "Índice del primer elemento", "fill", "Completa únicamente el índice usado para obtener GREAT.", "programas = [\"GREAT\", \"MPAS\", \"DARE\", \"PSCC\", \"VIF\"]\nprint(programas[___])", "0", "El primer elemento ocupa la posición 0."],
  ["Datos", "¿Qué es un diccionario?", "choice", "Selecciona la definición de la Lección 2.", ["Información relacionada organizada en pares de clave → valor.", "Una función sin parámetros.", "Una secuencia de acciones de un vehículo."], 0, "Un diccionario guarda información relacionada mediante pares clave → valor."],
  ["Datos", "Identifica una clave", "choice", "En el diccionario de la delegación, ¿cuál de estas opciones es una clave?", ["\"avance\"", "15", "20"], 0, "avance es el nombre de un dato, es decir, una clave del diccionario."],
  ["Datos", "Valor de avance", "fill", "Completa el valor de `avance` exactamente como aparece en el diccionario del ejemplo.", "delegacion = {\n  \"nombre\": \"Delegación Central\",\n  \"region\": \"Región 1\",\n  \"meta\": 20,\n  \"avance\": ___\n}", "15", "En el ejemplo, avance tiene el valor 15."],
  ["Datos", "Consulta el diccionario", "fill", "Completa únicamente la clave usada para imprimir el avance.", "print(delegacion[\"___\"])", "avance", "El material usa delegacion[\"avance\"] para consultar ese dato."],
  ["Datos", "Lista de diccionarios", "choice", "¿Cómo explica el material una lista de diccionarios?", ["Como una lista que contiene varios diccionarios, donde cada diccionario puede ser una fila de una tabla.", "Como una clase que contiene varios métodos.", "Como una función que solo retorna texto."], 0, "Una lista puede contener varios diccionarios y cada uno puede representar un registro."],
  ["Datos", "Conexión con Excel", "choice", "¿Qué comparación hace la Lección 2 entre una lista de diccionarios y una hoja de cálculo?", ["Cada registro puede representar una fila y cada clave una columna.", "Cada método representa una fila y cada objeto una fórmula.", "Cada lista representa un color y cada clave una imagen."], 0, "El material relaciona registros con filas y claves con columnas."],

  ["POO", "¿Qué es la POO?", "choice", "Selecciona la descripción dada en la Lección 2.", ["Una forma de organizar un programa representando elementos mediante objetos que reúnen datos y acciones relacionadas.", "Una técnica para contar posiciones desde 0.", "Una forma de evitar el uso de funciones."], 0, "La POO organiza datos y acciones relacionadas dentro de objetos."],
  ["POO", "Datos de un vehículo", "choice", "En el ejemplo cotidiano, ¿cuál grupo corresponde a datos del vehículo?", ["marca, modelo y color", "encender, acelerar y frenar", "meta, return y def"], 0, "Marca, modelo y color son características o datos del vehículo."],
  ["POO", "Acciones de un vehículo", "choice", "En el ejemplo cotidiano, ¿cuál grupo corresponde a acciones del vehículo?", ["marca, modelo y color", "encender, acelerar y frenar", "nombre, región y avance"], 1, "Encender, acelerar y frenar son acciones."],
  ["POO", "Concepto: clase", "choice", "¿Qué significa `Clase` según la tabla de conceptos esenciales?", ["Molde que define cómo serán los objetos.", "Elemento creado a partir de una clase.", "Dato o característica del objeto."], 0, "Una clase es el molde que define cómo serán los objetos."],
  ["POO", "Concepto: objeto", "choice", "¿Qué significa `Objeto` según la tabla?", ["Acción que puede realizar el objeto.", "Elemento creado a partir de una clase.", "Molde que define cómo serán los objetos."], 1, "Un objeto es un elemento creado a partir de una clase."],
  ["POO", "Concepto: atributo", "choice", "¿Qué significa `Atributo`?", ["Dato o característica del objeto.", "Acción que puede realizar el objeto.", "Palabra usada para devolver un resultado."], 0, "Un atributo es un dato o característica del objeto."],
  ["POO", "Concepto: método", "choice", "¿Qué significa `Método`?", ["Acción que puede realizar el objeto.", "Nombre de una fila en Excel.", "Valor almacenado en una lista."], 0, "Un método representa una acción que puede realizar el objeto."],
  ["POO", "Identifica la clase aplicada", "fill", "Completa únicamente el nombre de la clase utilizada en el ejemplo aplicado.", "class ___:\n    def __init__(self, nombre, region, meta, avance):\n        self.nombre = nombre", "Delegacion", "La clase del ejemplo se llama Delegacion."],
  ["POO", "Identifica el método", "fill", "Completa únicamente el nombre del método que muestra el resumen.", "def ___(self):\n    print(\"Delegación:\", self.nombre)\n    print(\"Avance:\", self.avance, \"de\", self.meta)", "mostrar_resumen", "El método del ejemplo se llama mostrar_resumen()."],
  ["POO", "Desafío final: clase y objeto", "multi", "Completa las dos piezas faltantes. Escribe las respuestas separadas por una coma, por ejemplo: `Delegacion, unidad`.", "class ___:\n    ...\n\n___ = Delegacion(\"Delegación Central\", \"Región 1\", 20, 15)\nunidad.mostrar_resumen()", ["Delegacion", "unidad"], "Identificaste correctamente la clase Delegacion y el objeto unidad del ejemplo aplicado."]
];

let state={i:0,correct:0,errors:0,firstTry:0,attempts:[],start:0,timer:null,name:"",solved:new Set(),category:{}};
const $=s=>document.querySelector(s);
const norm=s=>String(s).trim().replace(/\s+/g," ").toLowerCase();
function show(id){["welcome","quiz","results"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==id))}
function fmt(sec){return String(Math.floor(sec/60)).padStart(2,"0")+":"+String(sec%60).padStart(2,"0")}
function tick(){let s=Math.floor((Date.now()-state.start)/1000);$("#timer").textContent=fmt(s)}
function start(){
 state={i:0,correct:0,errors:0,firstTry:0,attempts:Array(30).fill(0),start:Date.now(),timer:null,name:$("#studentName").value.trim()||"Estudiante",solved:new Set(),category:{}};
 show("quiz");$("#hud").classList.remove("hidden");buildMap();render();state.timer=setInterval(tick,1000);tick()
}
function buildMap(){let m=$("#challengeMap");m.innerHTML="";challenges.forEach((_,i)=>{let b=document.createElement("button");b.textContent=i+1;b.disabled=true;m.appendChild(b)})}
function render(){
 let c=challenges[state.i], [cat,title,type,prompt,data,answer,explain]=c;
 $("#hudCurrent").textContent=state.i+1;$("#hudCorrect").textContent=state.correct;$("#progressBar").style.width=(state.i/30*100)+"%";
 $("#category").textContent=cat.toUpperCase();$("#difficulty").textContent=state.i<10?"INICIAL":state.i<22?"APLICACIÓN":"DESAFÍO";
 $("#challengeNumber").textContent=String(state.i+1).padStart(2,"0");$("#title").textContent=title;$("#prompt").textContent=prompt;
 $("#feedback").className="feedback hidden";$("#feedback").innerHTML="";$("#checkBtn").classList.remove("hidden");$("#nextBtn").classList.add("hidden");
 document.querySelectorAll("#challengeMap button").forEach((b,i)=>{b.className=state.solved.has(i)?"solved":i===state.i?"active":""});
 let w=$("#workspace");w.innerHTML="";
 if(type==="choice"){let o=document.createElement("div");o.className="options";data.forEach((x,i)=>{let b=document.createElement("button");b.className="option";b.textContent=x;b.dataset.v=i;b.onclick=()=>{o.querySelectorAll(".option").forEach(z=>z.classList.remove("selected"));b.classList.add("selected")};o.appendChild(b)});w.appendChild(o)}
 else {let box=document.createElement("div");box.className="codebox";box.innerHTML='<div class="codebar">ejercicio.py</div><pre></pre>';box.querySelector("pre").textContent=data;w.appendChild(box);let a=document.createElement("div");a.className="answer-wrap";a.innerHTML='<label>Completa únicamente lo que falta:</label><input id="answer" class="answer-input" autocomplete="off" spellcheck="false">';w.appendChild(a);setTimeout(()=>$("#answer")?.focus(),50)}
}
function check(){
 let c=challenges[state.i], [cat,title,type,prompt,data,answer,explain]=c, ok=false;state.attempts[state.i]++;
 if(type==="choice"){let s=document.querySelector(".option.selected");if(!s){feedback(false,"Selecciona una respuesta antes de comprobar.");return}ok=Number(s.dataset.v)===answer}
 else if(type==="multi"){let parts=$("#answer").value.split(",").map(norm);ok=parts.length===2&&parts[0]===norm(answer[0])&&parts[1]===norm(answer[1])}
 else {ok=norm($("#answer").value)===norm(answer)}
 if(ok){state.correct++;if(state.attempts[state.i]===1)state.firstTry++;state.solved.add(state.i);state.category[cat]=(state.category[cat]||{ok:0,total:0});state.category[cat].ok++;feedback(true,"✓ SOLUCIÓN CORRECTA",explain);$("#checkBtn").classList.add("hidden");$("#nextBtn").classList.remove("hidden");$("#hudCorrect").textContent=state.correct;document.querySelectorAll(".option").forEach(b=>b.disabled=true)}
 else {state.errors++;feedback(false,"Todavía hay un detalle por corregir.",hint(c))}
}
function hint(c){let cat=c[0];if(cat==="Funciones")return "Revisa la sección 1: funciones, parámetros, return y modularidad.";if(cat==="Datos")return "Revisa la sección 2: listas, diccionarios y la conexión con Excel.";if(cat==="POO")return "Revisa la sección 3: clase, objeto, atributo y método.";return "Revisa el concepto en el material de la Lección 2 antes de volver a probar."}
function feedback(ok,title,text=""){let f=$("#feedback");f.className="feedback "+(ok?"ok":"bad");f.innerHTML="<b>"+title+"</b>"+text}
function next(){if(state.i<29){state.i++;render()}else finish()}
function finish(){clearInterval(state.timer);let sec=Math.floor((Date.now()-state.start)/1000);$("#hud").classList.add("hidden");show("results");$("#resultName").textContent=state.name;$("#finalScore").textContent=state.correct+"/30";$("#finalTime").textContent=fmt(sec);$("#firstTry").textContent=state.firstTry;$("#totalErrors").textContent=state.errors;
 let totals={};challenges.forEach(c=>{totals[c[0]]=(totals[c[0]]||0)+1});let cr=$("#categoryResults");cr.innerHTML="";Object.entries(totals).forEach(([cat,total])=>{let ok=(state.category[cat]?.ok||0),p=Math.round(ok/total*100);cr.innerHTML+=`<div class="cat-row"><span>${cat}</span><div class="cat-bar"><i style="width:${p}%"></i></div><b>${p}%</b></div>`});
 let best=JSON.parse(localStorage.getItem("pa_l2_best")||"null"),msg="";if(!best||state.correct>best.score||(state.correct===best.score&&sec<best.time)){localStorage.setItem("pa_l2_best",JSON.stringify({score:state.correct,time:sec,name:state.name}));msg="★ NUEVO MEJOR RESULTADO PERSONAL"}else msg=`Mejor registro: ${best.score}/30 · ${fmt(best.time)}`;$("#recordMessage").textContent=msg;loadRecords()}
function loadRecords(){let b=JSON.parse(localStorage.getItem("pa_l2_best")||"null");$("#records").textContent=b?`Mejor registro guardado en este dispositivo: ${b.score}/30 · ${fmt(b.time)}`:"Aún no hay intentos guardados en este dispositivo."}
$("#startBtn").onclick=start;$("#checkBtn").onclick=check;$("#nextBtn").onclick=next;$("#restartBtn").onclick=()=>{show("welcome");loadRecords()};document.addEventListener("keydown",e=>{if(e.key==="Enter"&&$("#answer")&&!$("#checkBtn").classList.contains("hidden"))check()});loadRecords();
